// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kaneda_cocoroto_co

//@version=6
indicator("[2-2]RSI", overlay = false)

// input パラメータ設定
rsi_length = input.int(defval = 14, title = "長期RSI期間", minval = 1)
rsi_bottom_threshold = input.int(defval = 30, title = "RSIの下のしきい値", minval = 1)
rsi_center_under = input.int(defval = 45, title = "RSIセンターライン（下）", maxval = 50)
rsi_top_threshold = input.int(defval = 70, title = "RSIの上のしきい値", minval = 1)
rsi_center_over = input.int(defval = 55, title = "RSIセンターライン（上）", minval = 50)

// RSIの計算
rsi = ta.rsi(close, rsi_length)

// RSI のプロット
rsi_zero_line = hline(0, title = "0", color = color.gray, linestyle = hline.style_solid)
rsi_100_line = hline(100, title = "0", color = color.gray, linestyle = hline.style_solid)
rsi_bottom_threshold_line = hline(rsi_bottom_threshold, title = "RSI売られすぎ",
     color = color.blue, linestyle = hline.style_dotted)
rsi_center_under_line = hline(rsi_center_under, title = "RSIのセンター下",
     color = color.aqua, linestyle = hline.style_dashed)
rsi_top_threshold_line = hline(rsi_top_threshold, title = "RSI買われすぎ",
     color = color.red, linestyle = hline.style_dotted)
rsi_center_over_line = hline(rsi_center_over, title = "RSIのセンター上",
     color = color.purple, linestyle = hline.style_dashed)

plot(rsi, title = "RSI", color = color.yellow, linewidth = 2)
fill(rsi_zero_line, rsi_bottom_threshold_line, color = color.new(color.blue, transp = 80))
fill(rsi_top_threshold_line, rsi_100_line, color = color.new(color.red, transp = 80))