// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kaneda_cocoroto_co

//@version=6
strategy("[2]RSI、センターラインストラテジー", overlay=false, margin_long=100, margin_short=100)

// input パラメータ設定
rsi_length = input.int(defval = 14, title = "長期RSI期間", minval = 1)
rsi_bottom_threshold = input.int(defval = 30, title = "RSIの下のしきい値", minval = 1)
rsi_center_under = input.int(defval = 45, title = "RSIセンターライン（下）", maxval = 50)
rsi_top_threshold = input.int(defval = 70, title = "RSIの上のしきい値", minval = 1)
rsi_center_over = input.int(defval = 55, title = "RSIセンターライン（上）", minval = 50)

// ストラテジー機関の設定
time_from = input.time(defval = timestamp(dateString = "2024-01-01T00:00:00"),
     group = "バックテストの期間", title = "From")
time_To = input.time(defval = timestamp(dateString = "2024-12-31T00:00:00"),
     group = "バックテストの期間", title = "To")
isBetween = time_from <= time and time < time_To

// RSIの計算
rsi = ta.rsi(close, rsi_length)

// signal
// RSIが下からセンターライン下を交差したとき買い
// 逆に、RSIが上からセンターライン下を交差したとき売り
rsi_center_crossover = ta.crossover(rsi, rsi_center_over)
rsi_center_crossunder = ta.crossunder(rsi, rsi_center_under)

// RSI のプロット
rsi_zero_line = hline(0, title = "0", color = color.gray, linestyle = hline.style_solid)
rsi_100_line = hline(100, title = "100", color = color.gray, linestyle = hline.style_solid)
rsi_bottom_threshold_line = hline(rsi_bottom_threshold, title = "RSI売られすぎ",
     color = color.blue, linestyle = hline.style_dotted)
rsi_center_under_line = hline(rsi_center_under, title = "RSIのセンター下",
     color = color.aqua, linestyle = hline.style_dashed)
rsi_top_threshold_line = hline(rsi_top_threshold, title = "RSI買われすぎ",
     color = color.red, linestyle = hline.style_dotted)
rsi_center_over_line = hline(rsi_center_over, title = "RSIのセンター上",
     color = color.purple, linestyle = hline.style_dashed)

plot(rsi, title = "RSI", color = color.yellow, linewidth = 2)

plotshape(rsi_center_crossover, title = "買いのセンターライン", style = shape.labelup, color = color.yellow,
     text = "BUY", location = location.bottom)
plotshape(rsi_center_crossunder, title = "売りのセンターライン", style = shape.labeldown, color = color.aqua,
     text = "SELL", location = location.bottom)

fill(rsi_zero_line, rsi_bottom_threshold_line, color = color.new(color.blue, transp = 80))
fill(rsi_top_threshold_line, rsi_100_line, color = color.new(color.red, transp = 80))

// ポジショニング条件
longCondition = rsi_center_crossover
shortCondition = rsi_center_crossunder

// エントリー条件
if (isBetween)
    if (longCondition)
        strategy.entry("My Long Entry Id", strategy.long)
    if (shortCondition)
        strategy.entry("My Short Entry Id", strategy.short)

// エグジット条件
strategy.exit("My Long Exit Id", "My Long Entry id", profit = 1000, loss = 500)
strategy.exit("My Short Exit Id", "My Short Entry id", profit = 1000, loss = 500)
