// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kaneda_cocoroto_co

//@version=6
indicator("[2]RSI", overlay = false)

// input パラメータ設定
rsi_length = input.int(defval = 14, title = "長期RSI期間", minval = 1)
rsi_threshold = input.int(defval = 20, title = "RSIの下のしきい値", minval = 1)
rsi_up_threshold = input.int(defval = 80, title = "RSIの上のしきい値", minval = 1)

// RSIの計算
rsi = ta.rsi(close, rsi_length)

// RSI のプロット
rsi_zero_line = hline(0, title = "0", color = color.gray, linestyle = hline.style_dashed)
rsi_threshold_line = hline(rsi_threshold, title = "RSIのしきい値", color = color.blue, linestyle = hline.style_dotted)
plot(rsi, title = "RSI", color = color.yellow, linewidth = 2)
fill(rsi_zero_line, rsi_threshold_line, color = color.new(color.yellow, transp = 80))
