// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kaneda_cocoroto_co

// このスクリプトは、元になったスクリプトがあります。下記を参照。
// Original Script by
// © rumpypumpydumpy
// https://jp.tradingview.com/script/owlV88rj-Rank-Correlation-Index/

//@version=6
indicator("Rank Correlation Index", overlay = false)

// input
src = input(close, title="close")
short_len = input(9, title="RCI短期")
mid_len = input(26, title="RCI中期")
long_len = input(52, title="RCI長期")

overBought_zone = input.int(defval = 80, title = "買われすぎゾーン")
overSold_zone = input.int(defval = -80, title = "売られすぎゾーン")

f_rci(_src, _len)=>
    _sum = 0.0
    for _i = 0 to _len -1
        _p = _src[_i]
        _o = 1
        _s = 0
        for _j = 0 to _len - 1
            if _p < _src[_j]
                _o := _o + 1
            else if _p == _src[_j]
                _s := _s + 1
        _ord = _o + (_s -1) / 2
        _sum := _sum + math.pow(_i + 1 - _ord, 2)
    (1 - 6 * _sum / (_len * (math.pow(_len,2) - 1))) * 100

short_RCI = f_rci(src, short_len)
mid_RCI = f_rci(src, mid_len)
long_RCI = f_rci(src, long_len)

// plot
plot(short_RCI, title="RCI短期", color = color.red, linewidth = 2)
plot(mid_RCI, title="RCI中期", color = color.aqua, linewidth = 2)
plot(long_RCI, title="RCI長期", color = color.white, linewidth = 2)

hline(0)
maxLine = hline(100)
minLine = hline(-100),
overBoughtLine = hline(overBought_zone, title = "overBought", color = color.red, linestyle = hline.style_solid)
overSoldLine = hline(overSold_zone, title = "overSold", color = color.blue, linestyle = hline.style_solid)

fill(overBoughtLine, maxLine, color = color.new(#FF9100, 70))
fill(overSoldLine, minLine, color = color.new(#0000FF, 70))