// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kaneda_cocoroto_co

// 参考サイト：ストキャスティクスって使えるの？pineで検証！
// URL:https://fp-shima.ne.jp/2022/09/29/pine11/

//@version=5
indicator("ストキャスティクス")

// 入力
stok_range = input.int(defval = 9, title = "期間")

// 計算
// ストキャスティクス：ファストストキャスティクス %K
stok = ta.stoch(close, high, low, stok_range)

// ストキャスティクス：ファストストキャスティクスの%Dかつ、スローストキャスティクス %K
stod = ta.sma(stok, 3)

// スローストキャスティクスの%D
slowstod = ta.sma(stod, 3)

// シグナル
crossUp = ta.crossover(slowstod, 20)
crossDown = ta.crossunder(slowstod, 80)

// プロット
plot(stok)
plot(stod, color = color.white)
plot(slowstod, color = color.lime)

// プロット（シグナル）
plotshape(crossUp, style = shape.triangleup, location = location.bottom,
     color = color.green, size = size.small, title = "ロング エントリーアラート発生",
     text = "GC", textcolor = color.white)
plotshape(crossDown, style = shape.triangleup, location = location.bottom,
     color = color.red, size = size.small, title = "ロング エグジットアラート発生",
     text = "DC", textcolor = color.white)