// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kaneda_cocoroto_co

//@version=6
indicator(title = "trend-line and res-line", overlay = true)

// input 値を取得するバーの場所
forward = input.int(defval = 5, title = "点1：最近のローソク足のポイント", minval = 1, maxval = 31)
back = input.int(defval = 25, title = "点2：過去のローソク足のポイント", minval = 1, maxval = 62)
high_y_offset = input.int(defval = 200, title = "トレンドライン上：オフセット", minval = -10000, maxval = 10000)
low_y_offset = input.int(defval = 200, title = "トレンドライン下：オフセット", minval = -10000, maxval = 10000)

// トレンドライン上
var line1 = line.new(bar_index[0], high[0], bar_index, low, extend = extend.right, color = color.blue)
line.set_xy1(line1, bar_index[back], high[back])
line.set_xy2(line1, bar_index[forward], high[forward])
// var label1 = label.new(bar_index, high, text = "トレンドライン[high]",
//  style = label.style_label_lower_right, size = size.small)
// label.set_xy(label1,bar_index, line.get_price(line1, bar_index))

// highを上下にずらしたラインを描画
var line1_offset = line.new(bar_index[0], high[0], bar_index, low, extend = extend.right,
 color = color.blue, style = line.style_dotted)
line.set_xy1(line1_offset, bar_index[back], high[back] - high_y_offset)
line.set_xy2(line1_offset, bar_index[forward], high[forward] - high_y_offset)
// var label1_offset = label.new(bar_index, high, text = "トレンドライン[high-offset]",
//  style = label.style_label_lower_right, size = size.small)
// label.set_xy(label1_offset,bar_index, line.get_price(line1_offset, bar_index))

// トレンドライン下
var line2 = line.new(bar_index[0], high[0], bar_index, low, extend = extend.right, color = color.orange)
line.set_xy1(line2, bar_index[back], low[back])
line.set_xy2(line2, bar_index[forward], low[forward])
// var label2 = label.new(bar_index, low, text = "トレンドライン[low]",
//  style = label.style_label_lower_right, size = size.small)
// label.set_xy(label2,bar_index, line.get_price(line2, bar_index))

// lowを上下にずらしたラインを描画
var line2_offset = line.new(bar_index[0], high[0], bar_index, low, extend = extend.right,
 color = color.orange, style = line.style_dotted)
line.set_xy1(line2_offset, bar_index[back], low[back] + low_y_offset)
line.set_xy2(line2_offset, bar_index[forward], low[forward] + low_y_offset)
// var label2_offset = label.new(bar_index, high, text = "トレンドライン[low-offset]",
//  style = label.style_label_lower_right, size = size.small)
// label.set_xy(label2_offset,bar_index, line.get_price(line2_offset, bar_index))
